### ISSUE TITLE
Catkin_make issue

### ISSUE THREAD

**Issue by Rudy112** [MiguelARD/cloth_point_cloud_segmentation#1]
Excellent work and thanks for sharing! When I want to catkin_make this file, there are always some errors. It is 100% in the terminal, then many errors happen. Do you know how to fix this? Thanks so much for your help!

[100%] Linking CXX executable /home/wei/usr_ws/devel/lib/cloth_segmentation/cloth_segmentation
...

//usr/lib/x86_64-linux-gnu/libgdcmMSFF.so.2.8: undefined reference to `uuid_unparse@UUID_1.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFRewriteDirectory@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFGetSizeProc@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2.0: undefined reference to `TIFFSetErrorHandler@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFSetDirectory@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFReadScanline@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFNumberOfTiles@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2.0: undefined reference to `TIFFReadRGBAStrip@LIBTIFF_4.0'
collect2: error: ld returned 1 exit status
cloth_point_cloud_segmentation/darknet_ros/darknet_ros/CMakeFiles/darknet_ros.dir/build.make:219: recipe for target '/home/wei/usr_ws/devel/lib/darknet_ros/darknet_ros' failed
make[2]: *** [/home/wei/usr_ws/devel/lib/darknet_ros/darknet_ros] Error 1
CMakeFiles/Makefile2:1797: recipe for target 'cloth_point_cloud_segmentation/darknet_ros/darknet_ros/CMakeFiles/darknet_ros.dir/all' failed
make[1]: *** [cloth_point_cloud_segmentation/darknet_ros/darknet_ros/CMakeFiles/darknet_ros.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: warning: libopencv_imgcodecs.so.3.2, needed by /opt/ros/melodic/lib/libcv_bridge.so, may conflict with libopencv_imgcodecs.so.3.4
/usr/bin/ld: warning: libopencv_imgproc.so.3.4, needed by /home/wei/anaconda3/envs/cloth_seg/lib/libopencv_dnn.so.3.4.2, may conflict with libopencv_imgproc.so.3.2
/usr/bin/ld: warning: libopencv_core.so.3.4, needed by /home/wei/anaconda3/envs/cloth_seg/lib/libopencv_dnn.so.3.4.2, may conflict with libopencv_core.so.3.2
//home/wei/anaconda3/envs/cloth_seg/lib/libfontconfig.so.1: undefined reference to `FT_Done_MM_Var'
collect2: error: ld returned 1 exit status
cloth_point_cloud_segmentation/cloth_segmentation/CMakeFiles/cloth_segmentation.dir/build.make:362: recipe for target '/home/wei/usr_ws/devel/lib/cloth_segmentation/cloth_segmentation' failed
make[2]: *** [/home/wei/usr_ws/devel/lib/cloth_segmentation/cloth_segmentation] Error 1
CMakeFiles/Makefile2:2635: recipe for target 'cloth_point_cloud_segmentation/cloth_segmentation/CMakeFiles/cloth_segmentation.dir/all' failed
make[1]: *** [cloth_point_cloud_segmentation/cloth_segmentation/CMakeFiles/cloth_segmentation.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j16 -l16" failed

**Comment by MiguelARD** [comment]
It seems that the problem comes from the interaction between darknet_ros and OpenCV. First, I would try to build separately the suggested fork of [darknet_ros](https://github.com/tom13133/darknet_ros/tree/9f4843298576cbda949909f546d8757095cb9032).
